"""update documents table

Revision ID: dbc9074b3c38
Revises: d418bb6c48fe
Create Date: 2026-07-02 12:07:02.462067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbc9074b3c38"
down_revision: Union[str, Sequence[str], None] = "d418bb6c48fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("title", sa.String(), nullable=False))
    op.add_column(
        "documents",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column("documents", "content", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("documents", "filename")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column("documents", "content", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("documents", "updated_at")
    op.drop_column("documents", "created_at")
    op.drop_column("documents", "title")
    # ### end Alembic commands ###
